version: '3'
services:
  Afisha:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:7000"
    ports:
      - "8001:7000"
    depends_on:
      - database

  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: geeks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  database_data:
